// <auto-generated />
using System;
using Caesar.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caesar.Migrations
{
    [DbContext(typeof(CaesarContext))]
    partial class CaesarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Caesar.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Caesar.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("Expense")
                        .HasColumnType("REAL");

                    b.Property<double>("Income")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmallCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimeTrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now') || 'Z'");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("SmallCategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Caesar.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Caesar.Models.LargeCategory", b =>
                {
                    b.HasBaseType("Caesar.Models.Category");

                    b.HasDiscriminator().HasValue("LargeCategory");
                });

            modelBuilder.Entity("Caesar.Models.MediumCategory", b =>
                {
                    b.HasBaseType("Caesar.Models.Category");

                    b.Property<int>("LargeCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("LargeCategoryId");

                    b.HasDiscriminator().HasValue("MediumCategory");
                });

            modelBuilder.Entity("Caesar.Models.SmallCategory", b =>
                {
                    b.HasBaseType("Caesar.Models.Category");

                    b.Property<int>("MediumCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("MediumCategoryId");

                    b.HasDiscriminator().HasValue("SmallCategory");
                });

            modelBuilder.Entity("Caesar.Models.Item", b =>
                {
                    b.HasOne("Caesar.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Items")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caesar.Models.SmallCategory", "SmallCategory")
                        .WithMany("Items")
                        .HasForeignKey("SmallCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("SmallCategory");
                });

            modelBuilder.Entity("Caesar.Models.MediumCategory", b =>
                {
                    b.HasOne("Caesar.Models.LargeCategory", "LargeCategory")
                        .WithMany("MediumCategories")
                        .HasForeignKey("LargeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LargeCategory");
                });

            modelBuilder.Entity("Caesar.Models.SmallCategory", b =>
                {
                    b.HasOne("Caesar.Models.MediumCategory", "MediumCategory")
                        .WithMany()
                        .HasForeignKey("MediumCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediumCategory");
                });

            modelBuilder.Entity("Caesar.Models.PaymentMethod", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Caesar.Models.LargeCategory", b =>
                {
                    b.Navigation("MediumCategories");
                });

            modelBuilder.Entity("Caesar.Models.SmallCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
